"""manual_initial_schema

Revision ID: 35f2e3356b55
Revises:
Create Date: 2025-07-10 10:03:58.233000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from backend.app.models import UserRole, BrokerPreference # For Enum types

# revision identifiers, used by Alembic.
revision: str = '35f2e3356b55'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('features', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_plans_name'), 'subscription_plans', ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('mobile_number', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('CLIENT', 'ADMIN', 'PARTNER', name='userrole'), nullable=False),
    sa.Column('broker_preference', sa.Enum('ANGELONE', 'ZERODHA', 'UPSTOX', 'NONE', name='brokerpreference'), nullable=True),
    sa.Column('subscription_plan_id', sa.Integer(), nullable=True),
    sa.Column('broker_user_id', sa.String(), nullable=True),
    sa.Column('api_key_encrypted', sa.String(), nullable=True),
    sa.Column('api_secret_encrypted', sa.String(), nullable=True),
    sa.Column('access_token_encrypted', sa.String(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.String(), nullable=True),
    sa.Column('otp_secret', sa.String(), nullable=True),
    sa.Column('otp_sent_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified_email', sa.Boolean(), nullable=True),
    sa.Column('is_verified_mobile', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_mobile_number'), 'users', ['mobile_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_mobile_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')

    op.drop_index(op.f('ix_subscription_plans_name'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.drop_table('subscription_plans')

    # Drop Enum types if they were created by SQLAlchemy/PostgreSQL
    # This might require specific syntax depending on the DB and how Enums are handled.
    # For PostgreSQL, SAEnum creates user-defined types.
    sa.Enum(name='userrole').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='brokerpreference').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
